version: '3.8'

services:
  mairen_coin:
    container_name: mairen_coin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7008:3000"
    volumes:
      - .:/app
    command: npm start
