version: '3.9'

services:
  mairen_coin:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mairen_network
    restart: always
    ports:
      - "7008:7008"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app  # Mount the entire application directory
    command: npm run dev

networks:
  mairen_network:
